dataset:
  folder-path: 'Data/pain_study/'
  data-file: 'pain_grants.csv'
  test-file: 'test_data.csv'
  
model:
  bs: 25
  nt: 14
  epochs: 30
  drop_out: 0.2
  theta_act: "softplus"
  lr: 0.0005
  lambda_theta: 35.0
  lambda_alpha: 15.0
  path: '/nfs/turbo/umms-vgvinodv/users/zzhaozhe/pain_study'

